# optional use different local db for integration tests
# spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
# spring.datasource.username=postgres
# spring.datasource.password=password
# spring.datasource.driver-class-name=org.postgresql.Driver
